export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_INFOCARDS_PENDING = 'REQUEST_INFOCARDS_PENDING';
export const REQUEST_INFOCARDS_SUCCESS = 'REQUEST_INFOCARDS_SUCCESS';
export const REQUEST_INFOCARDS_FAILED = 'REQUEST_INFOCARDS_FAILED';